# Generated by Django 4.0.3 on 2023-01-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_alter_customer_address_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='href',
            field=models.CharField(default=9, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
