# Generated by Django 4.0.3 on 2023-01-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_alter_automobilevo_import_href_alter_sale_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='href',
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_date',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-25T20:57:16.613093+00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_price',
            field=models.PositiveIntegerField(default=69420),
            preserve_default=False,
        ),
    ]
