# Generated by Django 4.0.3 on 2023-01-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0008_remove_sale_href_alter_sale_sales_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
