# Generated by Django 4.0.3 on 2023-01-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0009_sale_sale_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_number',
            field=models.PositiveIntegerField(max_length=10, null=True, unique=True),
        ),
    ]
