# Generated by Django 4.0.3 on 2023-01-25 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_serviceappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='vin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service_rest.automobilevo'),
            preserve_default=False,
        ),
    ]
