# Generated by Django 4.0.3 on 2023-01-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_remove_automobilevo_is_vip_serviceappointment_is_vip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceappointment',
            old_name='vin',
            new_name='automobile',
        ),
    ]
