# Generated by Django 4.0.3 on 2023-01-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_rename_vin_serviceappointment_automobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceappointment',
            old_name='automobile',
            new_name='vin',
        ),
    ]
