# Generated by Django 4.0.3 on 2023-01-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_remove_automobilevo_is_vip_serviceappointment_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='href',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
